### ISSUE TITLE
Axolotl buckets are the black and purple box cubes

### ISSUE THREAD

**Issue by KooKooGH** [AkashiiKun/MoreAxolotlVariantsAPI-Common#14]
I have really like this mod but it really sucks when you hold it, its a cube, and when its in your inventory its a cube, would it be possible to make the ugly cubes go away?

**Comment by AkashiiKun** [comment]
That shouldn't be happening
Could you provide a log?

**Comment by KooKooGH** [comment]
hey, yea i can, btw this is the 1.20.1 version of the mavm mod

[01:33:22] [Worker-ResourceReload-1/WARN]: minecraft:item/axolotl_bucket_blue
java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.impl.client.model.loading.ModelLoadingEventDispatcher.loadModel(net.minecraft.resources.ResourceLocation)" because "this.fabric_eventDispatcher" is null
	at net.minecraft.client.resources.model.ModelBakery.handler$fma001$onLoadModel(ModelBakery.java:6128) ~[client-1.20.1-20230612.114412-srg.jar%231262!/:?]
	at net.minecraft.client.resources.model.ModelBakery.m_119362_(ModelBakery.java) ~[client-1.20.1-20230612.114412-srg.jar%231262!/:?]
	at net.minecraft.client.resources.model.ModelBakery.m_119341_(ModelBakery.java:243) ~[client-1.20.1-20230612.114412-srg.jar%231262!/:?]
	at net.minecraft.client.resources.model.ModelBakery.handler$ghi000$addModelHook(ModelBakery.java:5061) ~[client-1.20.1-20230612.114412-srg.jar%231262!/:?]
	at net.minecraft.client.resources.model.ModelBakery.m_119306_(ModelBakery.java:387) ~[client-1.20.1-20230612.114412-srg.jar%231262!/:?]
	at net.minecraft.client.resources.model.ModelBakery.<init>(ModelBakery.java:127) ~[client-1.20.1-20230612.114412-srg.jar%231262!/:?]
	at net.minecraft.client.resources.model.ModelManager.m_246505_(ModelManager.java:83) ~[client-1.20.1-20230612.114412-srg.jar%231262!/:?]
	at net.minecraft.client.resources.model.ModelManager.mdfbe2ca$lambda$loadModelPluginData$0$0(ModelManager.java:2569) ~[client-1.20.1-20230612.114412-srg.jar%231262!/:?]
	at java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1311) ~[?:?]
	at java.util.concurrent.CompletableFuture$BiApply.tryFire(CompletableFuture.java:1280) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
[01:33:22] [Worker-ResourceReload-1/WARN]: mavm:item/axolotl_bucket_lucia
java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.impl.client.model.loading.ModelLoadingEventDispatcher.loadModel(net.minecraft.resources.ResourceLocation)" because "this.fabric_eventDispatcher" is null

this error occurs when holding the axolotls in buckets, btw not only the lucia axolotl

**Comment by AkashiiKun** [comment]
But you're reporting the issue on the MAVAPI repository... Anyways the bucket textures are handled in the API so it's whatever
Please send the log as i need it to debug what's going on since you didn't even specify what modloader you're using.

**Comment by KooKooGH** [comment]
https://mclo.gs/OgaiDeR
sorry, I thought that this issue was related to MAVM as it says axolotl name (MAVM) completely my mistake, apologies

**Comment by AkashiiKun** [comment]
Apparently you have a mod that loads fabric mods on forge. That breaks the load of the custom axolotl textures and there is no other solution than remove that mod if you want to fix that, i'm sorry.

**Comment by KooKooGH** [comment]
ah alright I figured that would be the cause, thanks for helping me, sorry again for uploading the issue here
