### ISSUE TITLE
Crashes in Dev when using Yarn Mappings

### ISSUE THREAD

**Issue by Estecka** [AkashiiKun/MoreAxolotlVariantsAPI-Common#17]
I wanted to test the compatibility of this mod with another one I'm working on. However, mavapi causes a crash when I run it in my development environment. (The crash does not occur when using the same two mods in a regular minecraft instance !)

```log
java.lang.IllegalAccessError: Update to non-static final field net.minecraft.item.EntityBucketItem.entityType attempted from a different method (handler$zdb000$mavapi$onInit) than the initializer method <init>
        at net.minecraft.item.EntityBucketItem.handler$zdb000$mavapi$onInit(EntityBucketItem.java:568)
        at net.minecraft.item.EntityBucketItem.<init>(EntityBucketItem.java:48)
        at net.minecraft.item.Items.<clinit>(Items.java:1117)
```

Faulty code:
https://github.com/AkashiiKun/MoreAxolotlVariantsAPI-Common/blob/c692a509be0bab64b9a6087f6eed090409d98a27/Common/src/main/java/io/github/akashiikun/mavapi/v1/mixin/MobBucketItemMixin.java#L61-L68

With Yarn, the field `entityType` that you declare already exists in the base class (with mojmap you know it as simply `type`), so this mixin ends up shadowing the original final field instead of creating its own mutable one. 

The quickest fix would be to add `@Unique` to your own field. However at a glance, it looks like your field serves the same purpose as the original, so I'd suggest `@Shadow`ing it instead, and removing `onInit` completely.

**Comment by AkashiiKun** [comment]
Right... It's not a feature i added myself but my contributor and didn't bother to check as it works... Will fix in the next update.
